"""
Mock Database - Simulates a real DB with user financial profiles.
In production, replace with actual PostgreSQL/MongoDB queries.
"""

from typing import Optional, Dict, Any

# Sample users keyed by PAN number
MOCK_USERS: Dict[str, Dict[str, Any]] = {
    "ABCDE1234F": {
        "pan": "ABCDE1234F",
        "name": "Rahul Sharma",
        "aadhaar_last4": "5678",
        "phone": "9876543210",
        "email": "rahul.sharma@email.com",
        "AGE": 32,
        "GENDER": "M",
        "MARITALSTATUS": "Married",
        "EDUCATION": "GRADUATE",
        "NETMONTHLYINCOME": 45000,
        "Time_With_Curr_Empr": 36,
        "Credit_Score": 720,
        "num_times_delinquent": 0,
        "recent_level_of_deliq": 0,
        "num_deliq_6mts": 0,
        "num_deliq_12mts": 0,
        "num_times_30p_dpd": 0,
        "num_times_60p_dpd": 0,
        "num_std": 5,
        "num_sub": 0,
        "num_dbt": 0,
        "num_lss": 0,
        "tot_enq": 3,
        "enq_L12m": 2,
        "enq_L6m": 1,
        "time_since_recent_enq": 4,
        "CC_utilization": 25.0,
        "PL_utilization": 10.0,
        "max_unsec_exposure_inPct": 30.0,
        "pct_of_active_TLs_ever": 85.0,
        "pct_currentBal_all_TL": 40.0,
    },
    "PQRST5678G": {
        "pan": "PQRST5678G",
        "name": "Priya Mehta",
        "aadhaar_last4": "1234",
        "phone": "9123456789",
        "email": "priya.mehta@email.com",
        "AGE": 27,
        "GENDER": "F",
        "MARITALSTATUS": "Single",
        "EDUCATION": "POST-GRADUATE",
        "NETMONTHLYINCOME": 65000,
        "Time_With_Curr_Empr": 24,
        "Credit_Score": 760,
        "num_times_delinquent": 0,
        "recent_level_of_deliq": 0,
        "num_deliq_6mts": 0,
        "num_deliq_12mts": 0,
        "num_times_30p_dpd": 0,
        "num_times_60p_dpd": 0,
        "num_std": 8,
        "num_sub": 0,
        "num_dbt": 0,
        "num_lss": 0,
        "tot_enq": 2,
        "enq_L12m": 1,
        "enq_L6m": 0,
        "time_since_recent_enq": 8,
        "CC_utilization": 15.0,
        "PL_utilization": 0.0,
        "max_unsec_exposure_inPct": 20.0,
        "pct_of_active_TLs_ever": 95.0,
        "pct_currentBal_all_TL": 25.0,
    },
    "XYZAB9012H": {
        "pan": "XYZAB9012H",
        "name": "Vijay Kumar",
        "aadhaar_last4": "9012",
        "phone": "8765432109",
        "email": "vijay.kumar@email.com",
        "AGE": 45,
        "GENDER": "M",
        "MARITALSTATUS": "Married",
        "EDUCATION": "12TH",
        "NETMONTHLYINCOME": 18000,
        "Time_With_Curr_Empr": 12,
        "Credit_Score": 580,
        "num_times_delinquent": 3,
        "recent_level_of_deliq": 2,
        "num_deliq_6mts": 1,
        "num_deliq_12mts": 2,
        "num_times_30p_dpd": 3,
        "num_times_60p_dpd": 1,
        "num_std": 2,
        "num_sub": 2,
        "num_dbt": 1,
        "num_lss": 0,
        "tot_enq": 8,
        "enq_L12m": 5,
        "enq_L6m": 3,
        "time_since_recent_enq": 1,
        "CC_utilization": 85.0,
        "PL_utilization": 70.0,
        "max_unsec_exposure_inPct": 90.0,
        "pct_of_active_TLs_ever": 45.0,
        "pct_currentBal_all_TL": 85.0,
    },
    "LMNOP3456I": {
        "pan": "LMNOP3456I",
        "name": "Anita Singh",
        "aadhaar_last4": "3456",
        "phone": "7654321098",
        "email": "anita.singh@email.com",
        "AGE": 35,
        "GENDER": "F",
        "MARITALSTATUS": "Married",
        "EDUCATION": "GRADUATE",
        "NETMONTHLYINCOME": 35000,
        "Time_With_Curr_Empr": 60,
        "Credit_Score": 690,
        "num_times_delinquent": 1,
        "recent_level_of_deliq": 1,
        "num_deliq_6mts": 0,
        "num_deliq_12mts": 1,
        "num_times_30p_dpd": 1,
        "num_times_60p_dpd": 0,
        "num_std": 4,
        "num_sub": 1,
        "num_dbt": 0,
        "num_lss": 0,
        "tot_enq": 4,
        "enq_L12m": 2,
        "enq_L6m": 1,
        "time_since_recent_enq": 3,
        "CC_utilization": 45.0,
        "PL_utilization": 30.0,
        "max_unsec_exposure_inPct": 50.0,
        "pct_of_active_TLs_ever": 75.0,
        "pct_currentBal_all_TL": 55.0,
    },
}


def get_user_by_pan(pan: str) -> Optional[Dict[str, Any]]:
    """Fetch user profile from mock DB by PAN number."""
    return MOCK_USERS.get(pan.upper())


def get_all_pans():
    """Return list of all available PANs (for testing)."""
    return list(MOCK_USERS.keys())
